module.exports = {
  baseFontSize: '18px',
  baseLineHeight: '2rem',
  highlight: '#e6be00',
  headingColor: '#2E2E2E',
  bodyColor: '#494949',
  linkColor: '#2E2E2E',
  hoverColor: '#e6be00',
  captionColor: '#BDC8CC',
  white: '#fff',
  backgroundColor: '#fcfcfc',
  codeBackgroundColor: '#F5F4F2',
  fonts: [
    '-apple-system',
    'BlinkMacSystemFont',
    'Segoe UI',
    'Roboto',
    'Oxygen',
    'Ubuntu',
    'Cantarell',
    'Open Sans',
    'Helvetica Neue',
    'sans-serif',
  ],
}
